version: '3.8'

services:
  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: odoo -d odoo --db_user=odoo --db_password=odoo -i base, dark_mode_knk, spiffy_theme_backend
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  odoo-web-data:
    name: odoo-18-docker_odoo-web-data
  odoo-db-data:
    name: odoo-18-docker_odoo-db-data
